config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'
  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books

	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	belongs_to :author
	belongs_to :publisher
	
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books

	validates :name, presence: true,
	          length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :books

	validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add new Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author created"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    flash[:notice] = "Author udpated"
    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = "Autor removed"
    redirect_to authors_path
  end

  def index
    @authors = Author.all.order("last_name ASC")
  end

  def show
     @author = Author.find(params[:id])
     @authors = Author.all
     @books = @author.books
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    flash[:notice] = 'Book added'
    redirect_to books_path
    flash[:notice] = 'Book added'
  end

  def update
        @book = Book.find(params[:id])
        @book.update(book_params)
        flash[:notice] = 'Book updated'
        redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] == 'Book removed'
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
  def book_params
    params.require(:book).permit(:title, :category_id, :author_id,
    :publisher_id, :isbn, :price, :buy, :format, :year, :excerpt, :pages, :coverpath)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add new Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
     if @category.save
      flash[:notice] = "Category Created"
      
        redirect_to categories_path
    else
        render 'new'
    end
  end

  def update
     @category = Category.find(params[:id])
     @category.update(category_params)
     flash[:notice] = "Category updated"
     redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category removed"
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add new Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher created"
       redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update(publisher_params)
    flash[:notice] = "Publisher updated"
    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice] = "Publisher removed"
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all.order("name ASC")
  end

  def show
    @publisher = Publisher.find(params[:id])
    @publishers = Publisher.all
    @books = @publisher.books
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>This is the index site About</p>
<p>Taxidermy venmo unicorn air plant. Prism banjo portland chia PBR&B chicharrones. Snackwave try-hard marfa cloud bread yuccie vegan bicycle rights cray kinfolk intelligentsia live-edge helvetica. Helvetica cornhole brunch truffaut four dollar toast slow-carb before they sold out. Tattooed YOLO pinterest vice. Master cleanse artisan tilde keffiyeh deep v four dollar toast chillwave synth. Mixtape venmo selfies leggings gluten-free. Woke kinfolk taxidermy whatever intelligentsia blue bottle occupy hammock coloring book cardigan gochujang raclette shaman street art venmo. Fingerstache ennui mlkshk subway tile pok pok mixtape beard waistcoat humblebrag dreamcatcher blog aesthetic brunch taxidermy irony. Butcher snackwave umami venmo, normcore kitsch vaporware ennui.</p>
<h3>Card Deck</h3>
<div class="card-deck">
  <div class="card">
    
    <%= image_tag ('covers/beginning_php5.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    
    <%= image_tag ('covers/ajax_on_rails.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    
    <%= image_tag ('covers/html5_css3.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
<h3>Card Group</h3>
<div class="card-group">
  <div class="card">
    
    <%= image_tag ('covers/html5_css3.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
        <%= image_tag ('covers/php_cookbook.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
        <%= image_tag ('covers/ruby_on_rails_power.jpg'), class: 'card-img-top' %>
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit Author</h2>
<%= form_for @author do |f| %>
<!--Check for errors -->
<% if @author.errors.any? %>
<% @author.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>

<div class="form-group">
<%= f.label :first_name %>
<%= f.text_field :first_name, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :last_name %>
<%= f.text_field :last_name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', authors_path, class: 'btn btn-default' %>

<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>
<table class="table table-striped">
	<tr>
		<td>Author Name</td>
		<td>Actions</td>
	</tr>
	<% @authors.each do |author| %>
		<tr>
			<td><%= author.first_name %> <%= author.last_name %></td>
			<td><%= link_to "Edit", edit_author_path(author.id) %> | <%= link_to "Delete", author_path(author), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/authors/new.html.erb
<h2>Add new Author</h2>
<%= form_for @author do |f| %>
<!--Check for errors -->
<% if @author.errors.any? %>
<% @author.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>

<div class="form-group">
<%= f.label :first_name %>
<%= f.text_field :first_name, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :last_name %>
<%= f.text_field :last_name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', authors_path, class: 'btn btn-default' %>

<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>


<%= form_for @book do |f| %>

<div class="form-group">
<%= f.label :title %><br />
<%= f.text_field :title, class: 'form-control' %><br />
</div>

<div class="form-group">
<%= f.label :isbn %><br />
<%= f.text_field :isbn, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :category %><br />
<%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :author %><br />
<%= f.select :author_id, Author.all.collect{|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :publisher %><br />
<%= f.select :publisher_id, Publisher.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :format %><br />
<%= f.text_field :format, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :year %><br />
<%= f.text_field :year, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :coverpath %><br />
<%= f.text_field :coverpath, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :excerpt %><br />
<%= f.text_area :excerpt, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :pages %><br />
<%= f.number_field :pages, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :price %><br />
<%= f.text_field :price, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :buy %><br />
<%= f.text_field :buy, class: 'form-control' %><br />
</div>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', books_path, class: 'btn btn-default' %>
<% end %>

app/views/books/index.html.erb
<% @books.each_slice(4) do |book| %>

<div class="card-deck">
	
  <% book.each do |book| %>

  <div class="card">
    
    <%= image_tag (book.coverpath), class: 'card-img-top' %>
    <div class="card-body">
      <h5 class="card-title"><%= book.title %></h5>
      <p class="card-text">This is a wider card with supporting text.</p>
    </div>
    <%= link_to "Read more", book_path(book), class: "btn btn-info" %>
    <div class="card-footer">
      <small class="text-muted"><%= time_ago_in_words(book.created_at) %> ago</small>
    </div>
  </div>
   <% end %>
</div>
<% end %>

<div class="row">
<% @books.each do |book| %>
  <div class="col-md-4">

    <a href="/books/<%= book.id %>">
    <%= image_tag (book.coverpath), class: "book" %>
    <h4><%= link_to book.title, book_path(book) %></h4>
  </a>
  </div>
<% end %>
</div>

app/views/books/new.html.erb
<h1>Add New Book</h1>


<%= form_for @book do |f| %>

<div class="form-group">
<%= f.label :title %><br />
<%= f.text_field :title, class: 'form-control' %><br />
</div>

<div class="form-group">
<%= f.label :isbn %><br />
<%= f.text_field :isbn, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :category %><br />
<%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :author %><br />
<%= f.select :author_id, Author.all.collect{|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :publisher %><br />
<%= f.select :publisher_id, Publisher.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select one'},  class: 'form-control' %><br /><br />
</div>
<div class="form-group">
<%= f.label :format %><br />
<%= f.text_field :format, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :year %><br />
<%= f.text_field :year, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :coverpath %><br />
<%= f.text_field :coverpath, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :excerpt %><br />
<%= f.text_area :excerpt, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :pages %><br />
<%= f.number_field :pages, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :price %><br />
<%= f.text_field :price, class: 'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :buy %><br />
<%= f.text_field :buy, class: 'form-control' %><br />
</div>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', books_path, class: 'btn btn-default' %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
	<h2><%= @book.title %></h2>
	
	<div class="float-left">
	<%= image_tag (@book.coverpath) %>
	</div>
	<div class="float-left book-info">
		<h4>Book Info</h4>
		<ul>
			<li><strong>Category: </strong><%= @book.category.name %></li>
			<li><strong>Author: </strong><%= @book.author.first_name %> <%= @book.author.last_name %></li>
			<li><strong>Publisher: </strong><%= @book.publisher.name %></li>
			<li><strong>Year: </strong><%= @book.year %></li>
			<li><strong>ISBN: </strong><%= @book.isbn %></li>
			<li><strong>Format: </strong><%= @book.format %></li>
			<li><strong>Pages: </strong><%= @book.pages %></li>
		</ul>
		<%= link_to "Buy for " + @book.price , @book.buy , class: 'btn btn-success', target: '_blank' %>
	
</div>
	<div class="clearfix"></div>
	<br />
	<h4>Excerpt</h4>
	<p>
		<%= @book.excerpt %>
	</p>
	<h5>Admin Functions</h5>
	<%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
<!--Check for errors -->
<% if @category.errors.any? %>
<% @category.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
 
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>

<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<table class="table table-striped">
	<tr>
		<td>Category Name</td>
		<td>Actions</td>
	</tr>
	<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= link_to "Edit", edit_category_path(category.id) %> | <%= link_to "Delete", category_path(category), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h2>Add new Category</h2>

<%= form_for @category do |f| %>
<!--Check for errors -->
<% if @category.errors.any? %>
<% @category.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
 
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', categories_path, class: 'btn btn-default' %>

<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<div id="books-index">
	<% @books.each_slice(4) do |book| %>
	<div class="row">
		<% book.each do |book| %>
		<div class="col-md-3">
			<h3><%= book.title %></h3>
			
			<%= image_tag (book.coverpath) %>
		
			<%= link_to 'Read More', book_path(book), class: "btn btn-primary" %>
		</div>
		<% end %>
	</div>
	<% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="sticky-bottom">
	<div class="container">
		<p>Copyright &copy; 2017, All rights Reserved</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="container">
		<h1 class="align-middle">The BookStore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
	</div>
</header>

app/views/layouts/_navbar.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= image_tag("bootstrap-solid.svg", height: '30', width: '30', class: "d-inline-block align-top") %> Bootstrap
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    
    <ul class="navbar-nav">
      <li class="nav-item <%= params[:controller] == 'books' ? 'active' : '' %>">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= params[:controller] == 'about' ? 'active' : '' %>">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
      
      
      

    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Add New
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Book", new_book_path, class: "dropdown-item" %>
          <%= link_to "Category", new_category_path,class: "dropdown-item" %>
          <%= link_to "Author", new_author_path, class: "dropdown-item" %>
          <%= link_to "Publisher", new_publisher_path, class: "dropdown-item" %> 
        </div>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Manage
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          
          <%= link_to "Categories", categories_path,class: "dropdown-item" %>
          <%= link_to "Authors", authors_path, class: "dropdown-item" %>
          <%= link_to "Publishers", publishers_path, class: "dropdown-item" %> 
        </div>
      </li>
    </ul>

    
    
  </div>
</nav>
</div>

app/views/layouts/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class="well">
<h1>Location Info</h1>
<ul>
	<li>The Bookstore</li>
	<li>567 Masachusetts Ave, Unit 2</li>
	<li>Boston, MA 02177</li>
	<li>Phone: (617) 123 456 78</li>
	<li>email: support@bookstore.com</li>
</ul>
</div>

<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>

<div class="list-group">
	<% @categories.each do |category| %>
	<%= link_to category.name, category_path(category.id), class: "list-group-item" %>
	<% end %>
	

</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome' %> | Bookstore</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
 
 
 
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <div class="row">
        <div class="col-md-9">
          
          <!--Alerts & Messages -->
          <% if flash[:notice] %>
          <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>
          <% if flash[:alert] %>
          <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>

          <%= yield %>

        </div>

        <div class="col-md-3">
          <%= render 'layouts/sidebar' %>
        </div>
      </div>
    </div>
  

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2>Edit Publisher</h2>

<%= form_for @publisher do |f| %>
<!--Check for errors -->
<% if @publisher.errors.any? %>
<% @publisher.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', publishers_path, class: 'btn btn-default' %>

<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>
<table class="table table-striped">
	<tr>
		<td>Publisher Name</td>
		<td>Actions</td>
	</tr>
	<% @publishers.each do |publisher| %>
		<tr>
			<td><%= publisher.name %></td>
			<td><%= link_to "Edit", edit_publisher_path(publisher.id) %> | <%= link_to "Delete", publisher_path(publisher), method: :delete, data: {confirm: 'Are you sure'} %> </td>

		</tr>
	<% end %>
</table>

app/views/publishers/new.html.erb
<h2>Add new Publisher</h2>

<%= form_for @publisher do |f| %>
<!--Check for errors -->
<% if @publisher.errors.any? %>
<% @publisher.errors.full_messages.each do |msg| %>
<!-- Show errors -->
<div class="alert alert-danger"><%= msg %></div>
<% end %>
<% end %>
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %><br />
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<%= link_to 'Cancel', publishers_path, class: 'btn btn-default' %>

<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>